---
resources:
- name: trigger-every-3-minutes
  type: time
  source:
    interval: 3m
- name: tcp-smoke
  type: git
  source:
    uri: https://github.com/rhardt-pivotal/tcp-smoke    

jobs:
- name: tcp-smoke-job
  plan:
  - get: trigger-every-3-minutes
    trigger: true
  - get: tcp-smoke
  - task: run-smoke-script
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: starkandwayne/concourse
      run:
        path: tcp-smoke/test.sh
      params:
        TCP_APP_HOST: (( tcp-app-host ))
        TCP_APP_PORT: (( tcp-app-port ))
        EXPECTED_RESPONSE: (( expected-response ))
        


